// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcifDv9W8d_BbaQBYP6du5kcicqXagYYk',
    appId: '1:588771078309:web:7e5a9c2f1dab0b716c9d4c',
    messagingSenderId: '588771078309',
    projectId: 'fiacre-brand',
    authDomain: 'fiacre-brand.firebaseapp.com',
    databaseURL: 'https://fiacre-brand.firebaseio.com',
    storageBucket: 'fiacre-brand.appspot.com',
    measurementId: 'G-G316ZYDG3Y',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOgnaxW4yUvSCh3H75DJQIR1Pi3ewcnV8',
    appId: '1:588771078309:ios:cb6dd30cd894aba56c9d4c',
    messagingSenderId: '588771078309',
    projectId: 'fiacre-brand',
    databaseURL: 'https://fiacre-brand.firebaseio.com',
    storageBucket: 'fiacre-brand.appspot.com',
    iosBundleId: 'com.fiacregiraneza.mypersonalnotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOgnaxW4yUvSCh3H75DJQIR1Pi3ewcnV8',
    appId: '1:588771078309:ios:cb6dd30cd894aba56c9d4c',
    messagingSenderId: '588771078309',
    projectId: 'fiacre-brand',
    databaseURL: 'https://fiacre-brand.firebaseio.com',
    storageBucket: 'fiacre-brand.appspot.com',
    iosBundleId: 'com.fiacregiraneza.mypersonalnotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcifDv9W8d_BbaQBYP6du5kcicqXagYYk',
    appId: '1:588771078309:web:8d8a5f904d55f70a6c9d4c',
    messagingSenderId: '588771078309',
    projectId: 'fiacre-brand',
    authDomain: 'fiacre-brand.firebaseapp.com',
    databaseURL: 'https://fiacre-brand.firebaseio.com',
    storageBucket: 'fiacre-brand.appspot.com',
    measurementId: 'G-CNMQ5E3WNP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAojWAvo98RC-XPLl8tEB5QK7jbmCI-NMw',
    appId: '1:588771078309:android:f7cf540941393c3d6c9d4c',
    messagingSenderId: '588771078309',
    projectId: 'fiacre-brand',
    databaseURL: 'https://fiacre-brand.firebaseio.com',
    storageBucket: 'fiacre-brand.appspot.com',
  );

}